package com.agents.builder.common.core.constant;

public interface PermissionConstants {

    String APPLICATION_CREATE = "APPLICATION:CREATE";

    String APPLICATION_UPDATE = "APPLICATION:EDIT";

    String APPLICATION_DELETE = "APPLICATION:DELETE";

    String APPLICATION_READ= "APPLICATION:READ";

    String DATASET_CREATE = "DATASET:CREATE";

    String DATASET_UPDATE = "DATASET:EDIT";

    String DATASET_DELETE = "DATASET:DELETE";

    String DATASET_READ= "DATASET:READ";

    String TEAM_CREATE = "TEAM:CREATE";

    String TEAM_UPDATE = "TEAM:EDIT";

    String TEAM_DELETE = "TEAM:DELETE";

    String TEAM_READ= "TEAM:READ";

    String USER_CREATE = "USER:CREATE";

    String USER_UPDATE = "USER:EDIT";

    String USER_DELETE = "USER:DELETE";

    String USER_READ= "USER:READ";

    String MODEL_CREATE = "MODEL:CREATE";

    String MODEL_UPDATE = "MODEL:EDIT";

    String MODEL_DELETE = "MODEL:DELETE";

    String MODEL_READ= "MODEL:READ";

    String SETTING_CREATE = "SETTING:CREATE";

    String SETTING_UPDATE = "SETTING:EDIT";

    String SETTING_DELETE = "SETTING:DELETE";

    String SETTING_READ= "SETTING:READ";

    String FUNCTION_LIB_CREATE = "FUNCTION_LIB:CREATE";

    String FUNCTION_LIB_UPDATE = "FUNCTION_LIB:EDIT";

    String FUNCTION_LIB_DELETE = "FUNCTION_LIB:DELETE";

    String FUNCTION_LIB_READ= "FUNCTION_LIB:READ";
}
